version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"     # Jenkins 웹 UI: localhost:8081
      - "50000:50000"   # Jenkins 에이전트용 포트
    volumes:
      - jenkins_home:/var/jenkins_home
      # Optional: Docker socket 공유 시 (Jenkins가 Docker를 제어하게 하려면)
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Seoul
    networks:
      - my-network

  spring-app:
    build:
      context: src/main/java/com/springai
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"     # Spring Boot 앱: localhost:8080
    networks:
      - my-network
    depends_on:
      - jenkins

volumes:
  jenkins_home:

networks:
  my-network:
    driver: bridge
